config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/new'
  get 'todos/list'
  post 'todos', to: 'todos#create'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit', as: 'edit_todo'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete_todo'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def show
  	
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to todos_path
  end

  def update
    @todo.update(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo.destroy
    redirect_to todos_path
  end

  def complete
    @todo.completed= true
    @todo.save
    redirect_to todos_path
  end

  def list
    @todos = Todo.all
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

  def find_todo
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">TodoApp</a>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
         <li><%= link_to 'Index', todos_path %></li>
      <li><%= link_to 'List',todos_list_path %></li>
      <li><%= link_to 'Formulario',todos_new_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <link href="https://stackpath.bootstrapcdn.com/bootswatch/3.3.7/sandstone/bootstrap.min.css" rel="stylesheet" integrity="sha384-G3G7OsJCbOk1USkOY4RfeX1z27YaWrZ1YuaQ5tbuawed9IoreRDpWpTkZLXQfPm3" crossorigin="anonymous">

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="well">
    <%= form_with model: @todo, local: true do |t| %>
      <%= t.label :description, 'TU TAREA' %>
      <%= t.text_field :description %>
      <%= t.label :completed, 'COMPLETADO' %>
      <%= t.check_box :completed %>
      <%= t.submit "Enviar", class: "btn btn-warning" %>
    <% end %>
  </div>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<div class="container">
  <div class="col-lg-6">
    <% @todos.each do |todo| %>
    <h3 class="upp"> Tarea <%= todo.id %></h3>
    <div class="well"><p><%= todo.description %></p> <br> <p><strong><%= todo.completed %></strong></p></div>
    <%= link_to "Show ", todo, class: 'btn btn-primary' %>
    <%= link_to "Edit ", edit_todo_path(todo), class: 'btn btn-default' %>
    <%= link_to "Destroy ", todo, method: :delete, class: 'btn btn-danger' %>
    <%= link_to "Completed ", complete_todo_path(todo), class: 'btn btn-warning' %>
    <% end %> <br>
  </div>
 </div>

 <div class="box-todo container">
 	<div class="col-lg-6">
        <%= link_to "Crear una nueva tarea ", todos_new_path, class: 'boton btn btn-success btn-lg' %>
    </div>
 </div>

app/views/todos/list.html.erb
<div class="container">
  <div class="col-lg-6">
    <h3 class="upp">No completados</h3>
    <% @todos.each do |t| %>
    <% if t.completed == false %>
    <div class="well">
        <p><%= t.description%></p>
    </div>
    <% end %>
    <% end %>
  </div>

  <div class="container">
    <div class="col-lg-6">
    <h3 class="upp">Completados</h3>
    <% @todos.each do |t| %>
    <% if t.completed  %>
    <div class="well">
        <p><%= t.description%></p>
    </div>
    <% end %>
    <% end %>
  </div>
  </div>
 </div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<!-- <div class="col-lg-12">

	<h4> <%= @todo.description %></h4>
	<h4> <%= @todo.completed %></h4>
	<h4> <%= time_ago_in_words @todo.created_at%></h4>
</div> -->


<div class="col-lg-6">
	<div class="panel panel-primary">
  		<div class="panel-heading">
    	TAREA: <h3 class="panel-title"> <%= @todo.description %></h3>
  	</div>

   	<div class="panel-body">
    	COMPLETADO (TRUE) O NO COMPLETADO (FALSE): <h2 class="text-info"> <%= @todo.completed %></h2>
  	</div>

   	<div class="panel-heading">
    	HORA: <h3 class="panel-title">  <%= time_ago_in_words @todo.created_at%></h3>
  	</div>
	</div>
</div>